### ISSUE TITLE
Non complete install extension

### ISSUE THREAD

**Issue by sergeyklay** [aerospike-community/aerospike-client-php5#71]
Hello!

Can you please fix `post-install-cmd` so that it himself used `php-config --extension-dir` in order to move compiled extension.

For example, after installing, I see:

``` sh
$ sudo composer run-script post-install-cmd
...
Libraries have been installed in:
   /home/klay/tmp/vendor/aerospike/aerospike-client-php/src/aerospike/modules
```

It would be great if you could optimize this process so that it could be used without additional workarounds for automated installations (e.g. Vagrant/Docker)

See:

``` sh
$ php-config --extension-dir
```

**Comment by rbotzer** [comment]
Noted. The plan is to split build.sh apart so that it's a helper, but you can install manually without it, too.
